# Generated by Django 3.2.9 on 2022-01-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_auto_20220125_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
